version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: todoo-app-db
    environment:
      POSTGRES_DB: todoo-app-db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - '5432:5432'
